## Descrição

Esse arquivo apresenta a demonstração para os arquivos contidos nesse repositório e também para a geração dos resultados da comparação entre Hard e Soft decision.

## Demostração da decodificação de um código linear (8,4) usando Hard decision

A criação do código é feita a partir da sua matriz geradora
$$
\mathbb{G} = \begin{bmatrix}
0 & 1 & 1 & 1 & 1 & 0 & 0 & 0 \\
1 & 1 & 1 & 0 & 0 & 1 & 0 & 0 \\
1 & 1 & 0 & 1 & 0 & 0 & 1 & 0 \\
1 & 0 & 1 & 1 & 0 & 0 & 0 & 1
\end{bmatrix}
$$

In [1]:
from modules.linearcode import * 

G = np.array([[0,1,1,1,1,0,0,0],
              [1,1,1,0,0,1,0,0],
              [1,1,0,1,0,0,1,0],
              [1,0,1,1,0,0,0,1]]) # Matriz geradora

# Cria o codigo a partir da matriz G
code = LinearCode(G)

# Printa o arranjo padrão de forma tabelar usando o módulo tabulate
code.print_diagram()

╒══════════╤══════════╤══════════╤══════════╤══════════╤══════════╤══════════╤══════════╤══════════╤══════════╤══════════╤══════════╤══════════╤══════════╤══════════╤══════════╕
│ 00000000 │ 01111000 │ 11100100 │ 10011100 │ 11010010 │ 10101010 │ 00110110 │ 01001110 │ 10110001 │ 11001001 │ 01010101 │ 00101101 │ 01100011 │ 00011011 │ 10000111 │ 11111111 │
├──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ 10000000 │ 11111000 │ 01100100 │ 00011100 │ 01010010 │ 00101010 │ 10110110 │ 11001110 │ 00110001 │ 01001001 │ 11010101 │ 10101101 │ 11100011 │ 10011011 │ 00000111 │ 01111111 │
├──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┼──────────┤
│ 01000000 │ 00111000 │ 10100100 │ 11011100 │ 10010010 │ 11101010 │ 01110110 │ 00001110 │ 11110001 │ 10001001 

## Usando a objeto criado com a classe LinearCode é possível realizar outras operações

### Conhecer a matriz de paridade H

In [2]:
code.H

array([[1, 0, 0, 0, 0, 1, 1, 1],
       [0, 1, 0, 0, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 1, 0, 1],
       [0, 0, 0, 1, 1, 0, 1, 1]])

### Encontrar todas as palavras do código

In [3]:
code.codewords

[array([0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 1, 1, 1, 0, 0, 0]),
 array([1, 1, 1, 0, 0, 1, 0, 0]),
 array([1, 0, 0, 1, 1, 1, 0, 0]),
 array([1, 1, 0, 1, 0, 0, 1, 0]),
 array([1, 0, 1, 0, 1, 0, 1, 0]),
 array([0, 0, 1, 1, 0, 1, 1, 0]),
 array([0, 1, 0, 0, 1, 1, 1, 0]),
 array([1, 0, 1, 1, 0, 0, 0, 1]),
 array([1, 1, 0, 0, 1, 0, 0, 1]),
 array([0, 1, 0, 1, 0, 1, 0, 1]),
 array([0, 0, 1, 0, 1, 1, 0, 1]),
 array([0, 1, 1, 0, 0, 0, 1, 1]),
 array([0, 0, 0, 1, 1, 0, 1, 1]),
 array([1, 0, 0, 0, 0, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1])]

### Encontrar todos os líderes da classe lateral

In [6]:
code.get_leaders()

array(['00000000', '10000000', '01000000', '00100000', '00010000',
       '00001000', '00000100', '00000010', '00000001', '11000000',
       '10100000', '01100000', '10010000', '01010000', '00110000',
       '10001000'], dtype='<U8')

### Encontrar a síndrome de cada um dos líderes

In [8]:
code.get_liders_syndromes()

{'0000': '00000000',
 '1000': '10000000',
 '0100': '01000000',
 '0010': '00100000',
 '0001': '00010000',
 '0111': '00001000',
 '1110': '00000100',
 '1101': '00000010',
 '1011': '00000001',
 '1100': '11000000',
 '1010': '10100000',
 '0110': '01100000',
 '1001': '10010000',
 '0101': '01010000',
 '0011': '00110000',
 '1111': '10001000'}

### Encontrar a síndrome para cada um vetor com a mesma dimensão do código

In [9]:
code.get_syndromes('11001101')

'1110'

### Encontrar a distância mínima para o código

In [10]:
code.dmin

4

### Por fim, decodificar uma vetor recebido em uma palavra do código

#### Exemplo 1:

In [19]:
# Vetor original
V = '00110110'
# Padrão de erro
E = '00100000' 
# Vetor recebido
R = sum_mod(V, E)

code.decoderBSC(R)

'00110110'

#### Exemplo 2:

In [12]:
# Vetor original
V = '00011011'
# Padrão de erro
E = '01000010' 
# Vetor recebido
R = sum_mod(V, E)

code.decoderBSC(R)

'Unable to correct! Weight of the error pattern is 2 and it is only possible to correct the smaller weight equal to 1'

In [15]:
codewords_polar = [2 * codeword - 1 for codeword in code.codewords]
codewords_polar

[array([-1, -1, -1, -1, -1, -1, -1, -1]),
 array([-1,  1,  1,  1,  1, -1, -1, -1]),
 array([ 1,  1,  1, -1, -1,  1, -1, -1]),
 array([ 1, -1, -1,  1,  1,  1, -1, -1]),
 array([ 1,  1, -1,  1, -1, -1,  1, -1]),
 array([ 1, -1,  1, -1,  1, -1,  1, -1]),
 array([-1, -1,  1,  1, -1,  1,  1, -1]),
 array([-1,  1, -1, -1,  1,  1,  1, -1]),
 array([ 1, -1,  1,  1, -1, -1, -1,  1]),
 array([ 1,  1, -1, -1,  1, -1, -1,  1]),
 array([-1,  1, -1,  1, -1,  1, -1,  1]),
 array([-1, -1,  1, -1,  1,  1, -1,  1]),
 array([-1,  1,  1, -1, -1, -1,  1,  1]),
 array([-1, -1, -1,  1,  1, -1,  1,  1]),
 array([ 1, -1, -1, -1, -1,  1,  1,  1]),
 array([1, 1, 1, 1, 1, 1, 1, 1])]

In [16]:
A = 2* np.array(code.codewords).T - 1
A

array([[-1, -1,  1,  1,  1,  1, -1, -1,  1,  1, -1, -1, -1, -1,  1,  1],
       [-1,  1,  1, -1,  1, -1, -1,  1, -1,  1,  1, -1,  1, -1, -1,  1],
       [-1,  1,  1, -1, -1,  1,  1, -1,  1, -1, -1,  1,  1, -1, -1,  1],
       [-1,  1, -1,  1,  1, -1,  1, -1,  1, -1,  1, -1, -1,  1, -1,  1],
       [-1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1],
       [-1, -1,  1,  1, -1, -1,  1,  1, -1, -1,  1,  1, -1, -1,  1,  1],
       [-1, -1, -1, -1,  1,  1,  1,  1, -1, -1, -1, -1,  1,  1,  1,  1],
       [-1, -1, -1, -1, -1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1]])

In [20]:
R

[0, 0, 0, 1, 0, 1, 1, 0]

In [21]:
B = R @ A
B

array([-3, -1, -1,  1,  1, -1,  3,  1, -1, -3,  1, -1, -1,  1,  1,  3])

In [24]:
([1,0,1,0,1,1] == [1,1,1,0,1,1])

NameError: name 'counter' is not defined