In [1]:
from modules.linearcode import * 
from modules.aux_functions import *
import numpy as np

G = np.array([[0,1,1,1,1,0,0,0],
              [1,1,1,0,0,1,0,0],
              [1,1,0,1,0,0,1,0],
              [1,0,1,1,0,0,0,1]]) # Matriz geradora

code = LinearCode(G)

## Passo 1: Gerar uma sequência aleatórias de bits '0' e '1'

In [ ]:
# Gera uma sequência de bits a ser transmitida
n_symbols_sequence = 100 # 100 bits serão gerados 

tx_signal = np.round(np.random.rand(1,n_symbols_sequence))
tx_signal

## Passo 2: Agrupar os símbolos em blocos   

In [ ]:
## Separa os bits em blocos
n_symbols_block = 4

tx_signal_block = np.reshape(tx_signal, (int(n_symbols_sequence/n_symbols_block),n_symbols_block))
tx_signal_block

In [4]:
## Aplica os bits de paridade a cada bloco de acordo com a matriz G
tx_signal_wordblock = dot_mod(tx_signal_block, code.G)
tx_signal_wordblock

array([[1., 1., 0., 0., 1., 0., 0., 1.],
       [1., 1., 1., 0., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0., 0., 1., 1.],
       [0., 1., 1., 0., 0., 0., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 0., 0., 1., 0., 0.],
       [1., 1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 1., 0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1., 0., 1., 1.],
       [0., 0., 1., 1., 0., 1., 1., 0.],
       [1., 1., 0., 0., 1., 0., 0., 1.],
       [1., 1., 0., 1., 0., 0., 1., 0.],
       [1., 1., 0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 1., 1., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0., 1., 1.],
       [1., 1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 0., 0., 0., 1.],
       [1., 1., 1., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 1., 0., 1.],
       [1., 0., 0., 0., 0., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 

In [5]:
## Coloca os símbolos que serão enviados lado a lado em um lista
tx_signal_with_paritybits = np.reshape(tx_signal_wordblock,(1,int((n_symbols_sequence/n_symbols_block) * code.G.shape[1])))[0]
tx_signal_with_paritybits

array([1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0.,
       0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1.,
       1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1.,
       0., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1.,
       0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0.])

## Passo 3: Aplica a modulação que será usada no canal

In [6]:
## Aplica a modulação BPSK. Transformando os bits 0 em -1 e 1 em 1
tx_signal_with_paritybits_BPSK = (2*tx_signal_with_paritybits - 1)
tx_signal_with_paritybits_BPSK

array([ 1.,  1., -1., -1.,  1., -1., -1.,  1.,  1.,  1.,  1., -1., -1.,
        1., -1., -1., -1.,  1.,  1., -1., -1., -1.,  1.,  1., -1.,  1.,
        1., -1., -1., -1.,  1.,  1., -1.,  1., -1.,  1., -1.,  1., -1.,
        1.,  1.,  1.,  1., -1., -1.,  1., -1., -1.,  1.,  1., -1., -1.,
        1., -1., -1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.,  1., -1.,
       -1., -1.,  1.,  1., -1.,  1.,  1., -1., -1.,  1.,  1., -1.,  1.,
        1., -1.,  1.,  1., -1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.,
        1., -1., -1.,  1., -1.,  1.,  1., -1., -1.,  1., -1., -1.,  1.,
       -1., -1., -1.,  1.,  1., -1.,  1.,  1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,
       -1., -1.,  1., -1., -1.,  1., -1.,  1.,  1.,  1.,  1., -1., -1.,
       -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,
       -1., -1., -1.,  1.,  1.,  1.,  1., -1., -1.,  1., -1., -1., -1.,
       -1.,  1., -1.,  1.,  1., -1.,  1.,  1., -1., -1., -1., -1

## Passo 4: Cria o canal AWGN

In [7]:
## Cria o canal ruidoso  
mu = 0 # Média 0
sigma = 1 # Variância 1

# Número aleátorio baseado em uma distribuição gaussiana
real_part_random = np.random.normal(mu, sigma, (1,len(tx_signal_with_paritybits)))

# Número aleátorio baseado em uma distribuição gaussiana multiplicado por j para criar um número imaginário
imaginary_part_random = 1j*np.random.normal(mu, sigma, (1,len(tx_signal_with_paritybits)))

# Canal com componente real e imaginária
channel = (1/np.sqrt(2))*(real_part_random + imaginary_part_random)

## Passo 5: Adicionar o ruído aos bits transmitidos 

In [8]:
EcN0dBs = np.arange(11) 
EcN0dBs

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
## Adição de ruído

inter_EcN0dBs = 0 

# Símbolos recebidos
rx_signal = tx_signal_with_paritybits_BPSK + (10**(-EcN0dBs[inter_EcN0dBs]/20)) * channel

## Passo 6: Decodificação por softdecision

In [10]:
### Separar em blocos com o comprimento da palavra-código

rx_signal_wordblock = np.reshape(np.real(rx_signal),(int(n_symbols_sequence/n_symbols_block),code.G.shape[1]))

In [11]:
### Gera todas as palavras código para a matriz G
codewords_vector = np.array(code.codewords)

In [12]:
### Cria a matriz A a partir das palavras código
A = 2 * codewords_vector.T - 1

In [13]:
## Cria a matriz B a multiplicando o sinal recebido pela matriz B (A multiplicação é no campo dos reais)
B = rx_signal_wordblock @ A

In [14]:
### Cria uma lista para armazenar os valores da coluna em cada que linha que apresenta o maior valor e também o seu valor
max_col_index_and_value = list()

# Percorre as linhas e seleciona o valor mais alto e sua posição na linha
for B_row in B:
    max_col_index_and_value.append(max(enumerate(B_row), key=lambda index: index[1]))

In [15]:
## Decodificando as informações

# Isola as iformações referente ao índices da tupla 'max_col_index_and_value'
col_index = np.array(max_col_index_and_value, dtype=int).T[0]

# Função para converter um número decimal em binário. Obs: O valor do binário está espalhado para seguir a forma que o código foi criado anteriormente
dec2bit = lambda dec: [int(bit) for bit in '{:0{}b}'.format(dec, code.G.shape[0])][::-1]

# Concatena os bits para gerar o sinal de saída
rx_signal_softdecode = np.concatenate(([dec2bit(index) for index in col_index]))
rx_signal_softdecode

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0])

In [16]:
# Sinal transmitido original
np.array(tx_signal, dtype=int)

array([[1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
        0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
        0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
        0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
        0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0]])

In [17]:
## Verifica a ocorrencia de erro no sinal
num_error = sum(((tx_signal - rx_signal_softdecode) != 0)[0])
num_error

0

In [18]:
## Taxa de erro da decodificação por soft é 
rate_soft_error = num_error / n_symbols_sequence
rate_soft_error

0.0

# HARD

In [19]:
## Normaliza os valores acima de 0 para ser igual a 1
rx_signal_hardconversion = np.real(rx_signal) > 0
rx_signal_hardconversion = rx_signal_hardconversion.astype(int)
rx_signal_hardconversion

array([[1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
        0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
        1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
        1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
        1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
        1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
        1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
        1, 0]])

## Passo 6: Decodificação por hard decision

In [20]:
## Separa os bits recebidos em blocos de comprimento com o mesmo tamanho da palavra transmitida no canal
rx_signal_hard_wordblock = np.reshape(rx_signal_hardconversion, (int(n_symbols_sequence/n_symbols_block),G.shape[1]))
rx_signal_hard_wordblock

array([[1, 1, 1, 0, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0, 1, 1],
       [0, 1, 0, 1, 0, 0, 1, 0],
       [1, 1, 1, 0, 0, 1, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1, 0, 1, 1],
       [0, 0, 1, 1, 0, 1, 1, 0],
       [1, 1, 0, 0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0, 0, 1, 0],
       [1, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 1, 0, 1, 1],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 1],
       [1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 0, 0, 0, 1],
       [1, 1, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 1, 1, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 1, 1, 0, 1, 1, 0]])

In [21]:
## Calcula a síndrome para cada umas das palavras recebidas
words_syndrome = dot_mod(rx_signal_hard_wordblock, code.H.T)
words_syndrome

array([[0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 1, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [31]:
vector_error_pattern = np.array([code.get_liders_syndromes()[bit2str(syndrome)] for syndrome in words_syndrome])

In [32]:
vector_error_pattern

array([[0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
np.array(sum_mod(rx_signal_hard_wordblock.reshape(-1), vector_error_pattern.reshape(-1)))

array([1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0])

In [33]:
vector_error_pattern.reshape(-1)

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [37]:
code.H.T

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 1, 1],
       [1, 1, 1, 0],
       [1, 1, 0, 1],
       [1, 0, 1, 1]])

In [50]:
words_syndrome

array([[0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 1, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)