In [358]:
from modules.linearcode import * 
from modules.aux_functions import *
import numpy as np

G = np.array([[0,1,1,1,1,0,0,0],
              [1,1,1,0,0,1,0,0],
              [1,1,0,1,0,0,1,0],
              [1,0,1,1,0,0,0,1]]) # Matriz geradora

code = LinearCode(G)

## Passo 1: Gerar uma sequência aleatórias de bits '0' e '1'

In [359]:
# Gera uma sequência de bits a ser transmitida
n_symbols_sequence = 100 # 100 bits serão gerados 

tx_signal = np.round(np.random.rand(1,n_symbols_sequence))
tx_signal

array([[1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1.,
        0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1.,
        1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 0.,
        0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
        1., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
        1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
        0., 0., 1., 0.]])

## Passo 2: Agrupar os símbolos em blocos   

In [360]:
## Separa os bits em blocos
n_symbols_block = 4

tx_signal_block = np.reshape(tx_signal, (int(n_symbols_sequence/n_symbols_block),n_symbols_block))
tx_signal_block

array([[1., 1., 1., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 1., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 1.],
       [1., 1., 0., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 1., 1., 1.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [361]:
## Aplica os bits de paridade a cada bloco de acordo com a matriz G
tx_signal_wordblock = dot_mod(tx_signal_block, code.G)
tx_signal_wordblock

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 1., 1.],
       [1., 0., 1., 1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0., 0., 1., 1.],
       [0., 1., 1., 0., 0., 0., 1., 1.],
       [1., 0., 1., 1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 1., 0., 1., 1.],
       [1., 0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 0., 1., 1., 0.],
       [1., 0., 1., 1., 0., 0., 0., 1.],
       [1., 1., 1., 0., 0., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 1., 1., 0., 0.],
       [1., 0., 0., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 1., 1., 0., 1., 1.],
       [0., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 

In [362]:
## Coloca os símbolos que serão enviados lado a lado em um lista
tx_signal_with_paritybits = np.reshape(tx_signal_wordblock,(1,int((n_symbols_sequence/n_symbols_block) * code.G.shape[1])))[0]
tx_signal_with_paritybits

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1.,
       0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0.,
       1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1.,
       1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1.,
       1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0.])

## Passo 3: Aplica a modulação que será usada no canal

In [363]:
## Aplica a modulação BPSK. Transformando os bits 0 em -1 e 1 em 1
tx_signal_with_paritybits_BPSK = (2*tx_signal_with_paritybits - 1)
tx_signal_with_paritybits_BPSK

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1., -1.,  1.,
       -1.,  1., -1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.,  1., -1.,
       -1., -1., -1.,  1.,  1.,  1.,  1., -1.,  1.,  1., -1., -1., -1.,
        1., -1.,  1.,  1., -1., -1., -1.,  1.,  1., -1.,  1.,  1., -1.,
       -1., -1.,  1.,  1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.,  1.,
       -1.,  1., -1.,  1., -1.,  1., -1., -1., -1., -1.,  1.,  1., -1.,
        1.,  1.,  1., -1., -1.,  1.,  1.,  1., -1., -1., -1., -1.,  1.,
        1., -1.,  1.,  1., -1.,  1., -1.,  1.,  1., -1., -1., -1.,  1.,
        1.,  1.,  1., -1., -1.,  1., -1., -1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1., -1., -1.,  1., -1., -1.,  1., -1.,
       -1.,  1.,  1.,  1., -1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.,
       -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,
        1., -1., -1., -1.,  1.,  1., -1., -1.,  1., -1., -1.,  1., -1.,
        1., -1.,  1., -1.,  1., -1.,  1., -1., -1., -1.,  1.,  1

## Passo 4: Cria o canal AWGN

In [364]:
## Cria o canal ruidoso  
mu = 0 # Média 0
sigma = 1 # Variância 1

# Número aleátorio baseado em uma distribuição gaussiana
real_part_random = np.random.normal(mu, sigma, (1,len(tx_signal_with_paritybits)))

# Número aleátorio baseado em uma distribuição gaussiana multiplicado por j para criar um número imaginário
imaginary_part_random = 1j*np.random.normal(mu, sigma, (1,len(tx_signal_with_paritybits)))

# Canal com componente real e imaginária
channel = (1/np.sqrt(2))*(real_part_random + imaginary_part_random)

## Passo 5: Adicionar o ruído aos bits transmitidos 

In [365]:
EcN0dBs = np.arange(11) 
EcN0dBs

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [348]:
## Adição de ruído

inter_EcN0dBs = 0 

# Símbolos recebidos
rx_signal = tx_signal_with_paritybits_BPSK + (10**(-EcN0dBs[inter_EcN0dBs]/20)) * channel

## Passo 6: Decodificação por softdecision

In [366]:
### Separar em blocos com o comprimento da palavra-código

rx_signal_wordblock = np.reshape(np.real(rx_signal),(int(n_symbols_sequence/n_symbols_block),code.G.shape[1]))

In [371]:
### Gera todas as palavras código para a matriz G
codewords_vector = np.array(code.codewords)

In [351]:
### Cria a matriz A a partir das palavras código
A = 2 * codewords_vector.T - 1

In [352]:
## Cria a matriz B a multiplicando o sinal recebido pela matriz B (A multiplicação é no campo dos reais)
B = rx_signal_wordblock @ A

In [353]:
### Cria uma lista para armazenar os valores da coluna em cada que linha que apresenta o maior valor e também o seu valor
max_col_index_and_value = list()

# Percorre as linhas e seleciona o valor mais alto e sua posição na linha
for B_row in B:
    max_col_index_and_value.append(max(enumerate(B_row), key=lambda index: index[1]))

In [354]:
## Decodificando as informações

# Isola as iformações referente ao índices da tupla 'max_col_index_and_value'
col_index = np.array(max_col_index_and_value, dtype=int).T[0]

# Função para converter um número decimal em binário. Obs: O valor do binário está espalhado para seguir a forma que o código foi criado anteriormente
dec2bit = lambda dec: [int(bit) for bit in '{:0{}b}'.format(dec, code.G.shape[0])][::-1]

# Concatena os bits para gerar o sinal de saída
rx_signal_softdecode = np.concatenate(([dec2bit(index) for index in col_index]))
rx_signal_softdecode

array([1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0])

In [355]:
# Sinal transmitido original
np.array(tx_signal, dtype=int)

array([[1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
        1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
        0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0]])

In [356]:
## Verifica a ocorrencia de erro no sinal
num_error = sum(((tx_signal - rx_signal_softdecode) != 0)[0])
num_error

3

In [357]:
## Taxa de erro da decodificação por soft é 
rate_soft_error = num_error / n_symbols_sequence
rate_soft_error

0.03

# HARD

In [10]:
## Normaliza os valores acima de 0 para ser igual a 1
rx_signal_hardconversion = np.real(rx_signal) > 0
rx_signal_hardconversion = rx_signal_hardconversion.astype(int)
rx_signal_hardconversion

array([[1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
        1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
        0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 0]])

## Passo 6: Decodificação por hard decision

In [11]:
## Separa os bits recebidos em blocos de comprimento com o mesmo tamanho da palavra transmitida no canal
rx_signal_hard_wordblock = np.reshape(rx_signal_hardconversion, (int(n_symbols_sequence/n_symbols_block),G.shape[1]))
rx_signal_hard_wordblock

array([[1, 0, 0, 1, 0, 1, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 1, 1, 1, 1, 0, 0],
       [1, 0, 1, 1, 1, 1, 1, 0],
       [1, 0, 1, 1, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 1, 1],
       [1, 0, 1, 1, 0, 0, 0, 1],
       [0, 1, 1, 1, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 1, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 1, 1, 1, 0, 1, 1],
       [0, 1, 1, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 1, 1, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1, 0, 0, 1],
       [0, 1, 0, 0, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 0, 1, 1, 1],
       [0, 1, 0, 0, 1, 1, 1, 0]])

In [12]:
## Calcula a síndrome para cada umas das palavras recebidas
words_syndrome = dot_mod(rx_signal_hard_wordblock, code.H.T)
words_syndrome

array([[0, 1, 1, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 0],
       [1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 1],
       [1, 1, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 1, 1],
       [0, 0, 0, 0]], dtype=int32)

In [13]:
# Cria uma matriz de zeros
syndrome_dec = np.zeros((len(words_syndrome),1))

In [14]:
# Opera os bits das síndrome multiplicando por 2 e elevando a sua posição 
for index_words_syndrome, inter_words_syndrome in enumerate(words_syndrome):
    syndrome_dec[index_words_syndrome] = sum([bit_words_syndrome*2**index for index, bit_words_syndrome in enumerate(inter_words_syndrome[::-1])])

In [15]:
# Substitui os zeros por 1
syndrome_dec[syndrome_dec == 0] = 1

In [16]:
# Cria uma matriz de zeros
bit_corr_idx = np.zeros((len(syndrome_dec),1))

In [17]:
for index in range(len(syndrome_dec)):
    bit_corr_idx[index] = bitIdx[int(syndromeDec[i])-1]

NameError: name 'bitIdx' is not defined

In [ ]:

    bitCorrIdx = np.zeros((len(syndromeDec),1))
    for i in range(len(syndromeDec)):
        bitCorrIdx[i] = bitIdx[int(syndromeDec[i])-1]
    bitCorrIdx = np.reshape(np.arange(N/4)*7,(int(N/4),1)) + bitCorrIdx #finding the index in the array
    for i in range(len(bitCorrIdx)):
        cipHard[0][int(bitCorrIdx[i])-1] = not(cipHard[0][int(bitCorrIdx[i])-1]) #correcting bits
    idx = np.kron(np.ones((1,int(N/4))), np.arange(1,5)) + np.kron(np.arange(N/4)*7,np.ones((1,4))) #index of data bits
    ipHat_hard = np.zeros((1,len(idx[0])))
    for i in range(len(idx[0])):
        ipHat_hard[0][i] = int(cipHard[0][int(idx[0][i])-1]) #selecting data bits